export const fragmentsLexicon100 = [
  { nidalum: 'ORAA', french: 'Souffle, vie, essence', english: 'Breath, life essence' },
  { nidalum: 'RA', french: 'Soleil, présence souveraine', english: 'Sun, sovereign presence' },
  { nidalum: 'SOUMA', french: 'Source, origine', english: 'Source, origin' },
  { nidalum: 'LUMÉ', french: 'Lumière', english: 'Light' },
  { nidalum: 'LUMERA', french: 'Chant de lumière, lumière chantée', english: 'Song of light, luminous chant' },
  { nidalum: 'ASHÂLIM', french: 'Parole sacrée', english: 'Sacred utterance' },
  { nidalum: 'ASHÂLIMORA', french: 'Mémoire de l\'origine', english: 'Memory of origin' },
  { nidalum: 'TÉ', french: 'À toi, vers toi', english: 'To you, toward you' },
  { nidalum: 'TÉ-LUMÉ', french: 'Lumière vers toi, chant de lumière personnel', english: 'Light toward you, personal light song' },
  { nidalum: 'KINTAYA', french: 'Harmonie, paix profonde', english: 'Harmony, deep peace' },
  { nidalum: 'AMUNÉ', french: 'Force invisible', english: 'Invisible strength' },
  { nidalum: 'HEKA', french: 'Courage sacré', english: 'Sacred courage' },
  { nidalum: 'SETU', french: 'Respect, limite, stop', english: 'Boundary, respect, stop' },
  { nidalum: 'ASHAÉ', french: 'Paix, calme', english: 'Peace, calm' },
  { nidalum: 'SARUNÉ', french: 'Célébration, danse', english: 'Celebration, dance' },
  { nidalum: 'ZÉTHRA', french: 'Patience, attente', english: 'Patience, waiting' },
  { nidalum: 'VENTUS', french: 'Respiration profonde', english: 'Breath, deep inhale' },
  { nidalum: 'FALÉH', french: 'Joie', english: 'Joy, happiness' },
  { nidalum: 'NARA', french: 'Faim', english: 'Hunger' },
  { nidalum: 'NÉLA', french: 'Soif', english: 'Thirst' },
  { nidalum: 'NELU', french: 'Boire', english: 'To drink' },
  { nidalum: 'DEMAÉ', french: 'Froid', english: 'Cold' },
  { nidalum: 'TESHAR', french: 'Chaud', english: 'Heat' },
  { nidalum: 'NÉRÚM', french: 'Tristesse', english: 'Sadness' },
  { nidalum: 'SESHRA', french: 'Réflexion, écoute', english: 'Reflection, listening' },
  { nidalum: 'KARAÉ', french: 'Force, vitalité', english: 'Strength, vitality' },
  { nidalum: 'NESHRA', french: 'Perdu, désorienté', english: 'Lost, disoriented' },
  { nidalum: 'LEMEKH', french: 'Inquiétude', english: 'Worry, unease' },
  { nidalum: 'RENEKA', french: 'Fierté', english: 'Pride, dignity' },
  { nidalum: 'MERUN', french: 'Inspiration', english: 'Inspiration' },
  { nidalum: 'RASHA', french: 'Épuisement', english: 'Exhaustion' },
  { nidalum: 'SESHUMA', french: 'Confusion', english: 'Confusion' },
  { nidalum: 'DÉNUR', french: 'Créer', english: 'To create' },
  { nidalum: 'NÉRAH', french: 'Voir, observer', english: 'To see, to witness' },
  { nidalum: 'SUMAÉ', french: 'Penser', english: 'To think' },
  { nidalum: 'TUMAÉ', french: 'Chanter', english: 'To sing' },
  { nidalum: 'TORAVAY', french: 'Travailler avec courage', english: 'To work with courage' },
  { nidalum: 'ARAMA', french: 'Prier, chant rituel', english: 'To pray, ritual chant' },
  { nidalum: 'ORÚ', french: 'Se préparer', english: 'To prepare' },
  { nidalum: 'EL', french: 'Rite, marque d\'élévation', english: 'Rite, elevation marker' },
  { nidalum: 'KERAL', french: 'Monter, grimper', english: 'To climb' },
  { nidalum: 'NÉLU', french: 'Souffle frais, purification', english: 'Fresh breath, purification' },
  { nidalum: 'FURAÉ', french: 'S\'échauffer', english: 'Warm up, awaken the body' },
  { nidalum: 'TÉRAH', french: 'Marcher', english: 'To walk' },
  { nidalum: 'FALUN', french: 'Manger', english: 'To eat' },
  { nidalum: 'RÉMORA', french: 'Se laver', english: 'To wash' },
  { nidalum: 'FERUM', french: 'Construire, façonner', english: 'To build, to craft' },
  { nidalum: 'ZORATH', french: 'Méditer', english: 'To meditate' },
  { nidalum: 'YARANÂ', french: 'Désir, être avec', english: 'Desire, to be with' },
  { nidalum: 'LURASH', french: 'Avancer', english: 'Advance, move forward' },
  { nidalum: 'ZESHU', french: 'Apprendre', english: 'To learn' },
  { nidalum: 'FERULAN', french: 'Clarifier', english: 'To clarify' },
  { nidalum: 'MERESHA', french: 'Rêver', english: 'To dream' },
  { nidalum: 'ANUTÉ', french: 'Renaissance', english: 'Rebirth' },
  { nidalum: 'OHALEM', french: 'Partir', english: 'To depart' },
  { nidalum: 'UNESHA', french: 'Se reposer', english: 'To rest' },
  { nidalum: 'VESRA', french: 'Soutien', english: 'Support' },
  { nidalum: 'RATEL', french: 'Lumière recherchée', english: 'Light sought, illumination' },
  { nidalum: 'QUARA', french: 'Signe, présage', english: 'Sign, omen' },
  { nidalum: 'TOÉN', french: 'Toi, est ce que tu', english: 'You, do you' },
  { nidalum: 'ORUM', french: 'Prêt', english: 'Ready' },
  { nidalum: 'NIDALUM', french: 'La langue, la Maison', english: 'The language, the House' },
  { nidalum: 'NIDAR', french: 'Force intérieure', english: 'Inner power' },
  { nidalum: 'YENDAH', french: 'Mémoire, résonance', english: 'Memory, resonance' },
  { nidalum: 'ZALAM', french: 'Vide, oubli', english: 'Void, oblivion' },
  { nidalum: 'NOOR', french: 'Lumière qui révèle', english: 'Light that reveals' },
  { nidalum: 'MORAE', french: 'Origine, commencement', english: 'Origin, beginning' },
  { nidalum: 'AHAD', french: 'Unité, le Un', english: 'Unity, the One' },
  { nidalum: 'KINA', french: 'Lien, clé, nœud', english: 'Bond, key, knot' },
  { nidalum: 'SHIM', french: 'Cœur, centre', english: 'Heart, center' },
  { nidalum: 'OKH', french: 'Feu, rage sacrée', english: 'Fire, sacred rage' },
  { nidalum: 'VAE', french: 'Vérité absolue', english: 'Truth, absolute reality' },
  { nidalum: 'RETH', french: 'Mort, effondrement', english: 'Death, end, collapse' },
  { nidalum: 'MATA', french: 'Eau, flux', english: 'Water, flow' },
  { nidalum: 'KORA', french: 'Vent, mouvement', english: 'Wind, movement' },
  { nidalum: 'ROUM', french: 'Pierre, stabilité', english: 'Stone, stability' },
  { nidalum: 'SAMA', french: 'Ciel, domaine supérieur', english: 'Sky, upper realm' },
  { nidalum: 'KIRIS', french: 'Lame', english: 'Blade, edge' },
  { nidalum: 'DAE', french: 'Sang, vie brute', english: 'Blood, raw life' },
  { nidalum: 'MAKHIM', french: 'Gardien, protecteur', english: 'Guardian, protector' },
  { nidalum: 'VARA', french: 'Bouclier, protection', english: 'Shield, protection' },
  { nidalum: 'SULAMA', french: 'Silence, pause sacrée', english: 'Silence, sacred pause' },
  { nidalum: 'SULAMARI', french: 'Les Oublieux', english: 'The forgetful ones' },
  { nidalum: 'PAURA', french: 'Peur ancienne', english: 'Fear, ancient anxiety' },
  { nidalum: 'KA\'LUM', french: 'Énergie vitale', english: 'Vital energy' },
  { nidalum: 'BA\'NIDAL', french: 'Âme vibrante', english: 'Vibrant soul' },
  { nidalum: 'RA\'LUM', french: 'Soleil interne', english: 'Inner sun' },
  { nidalum: 'KHEM\'FALÉ', french: 'Force terrestre', english: 'Earth force' },
  { nidalum: 'LUM\'AMUN', french: 'Lumière cachée', english: 'Hidden light' },
  { nidalum: 'NEF\'ARA', french: 'Beauté divine', english: 'Divine beauty' },
  { nidalum: 'SHEMU', french: 'Cycle des saisons', english: 'Season cycle' },
  { nidalum: 'AKET\'LUM', french: 'Horizon illuminé', english: 'Illuminated horizon' },
  { nidalum: 'TERU\'KA', french: 'Racine vitale', english: 'Vital root' },
  { nidalum: 'MERU\'SA', french: 'Temple vivant', english: 'Living temple' },
  { nidalum: 'ASHEM\'URA', french: 'Écriture sacrée', english: 'Sacred writing' },
  { nidalum: 'HEK\'LUM', french: 'Magie de lumière', english: 'Light magic' },
  { nidalum: 'SAHU\'RA', french: 'Corps solaire', english: 'Solar body' },
  { nidalum: 'KARA\'NEB', french: 'Flamme royale', english: 'Royal flame' },
  { nidalum: 'NEB\'SERU', french: 'Étoile ancestrale', english: 'Ancestral star' },
  { nidalum: 'RA\'KETESH', french: 'Porte du soleil', english: 'Gate of the sun' },
  { nidalum: 'LUM\'ZETH', french: 'Éclat du temps', english: 'Spark of time' },
];
